name: Mirror to Private
on:
  push:
    branches: [master]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Install Copybara
        run: |
          curl -sSL -o copybara.jar \
            https://github.com/google/copybara/releases/latest/download/copybara_deploy.jar
          echo "COPYBARA=java -jar $PWD/copybara.jar" >> $GITHUB_ENV
      - name: SSH for private push
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Run Copybara
        run: $COPYBARA migrate copybara/public_to_private.sky public_to_private
