name: Mirror to Private
on:
  push:
    branches: [master]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - name: Install Copybara
        run: |
          curl -sSL -o copybara.jar \
            https://github.com/google/copybara/releases/latest/download/copybara_deploy.jar
          echo "COPYBARA=java -jar $PWD/copybara.jar" >> $GITHUB_ENV
      - name: SSH for private push
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Set Git identity
        run: |
          git config --global user.name  "copybara-bot"
          git config --global user.email "copybara-bot@users.noreply.github.com"
      - name: Run Copybara
        run: $COPYBARA migrate --init-history --force copybara/copy.bara.sky public_to_private
